apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dz3
spec:
  selector:
    app: my-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: http-alt
    protocol: TCP
    port: 8080
    targetPort: 8080
